services:
  db:
    container_name: postgres_container
    image: postgres:16
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: pass
      POSTGRES_DB: multilabs_db
    volumes:
      - pg_data_app:/var/lib/postgresql/data
    networks:
      - app_multilabs

  app:
    container_name: app_multilabs
    build: .
    environment:
      URI_DATABASE: postgres_container
      PORT_DATABASE: 5432
      NAME_DATABASE: multilabs_db
      USER_DATABASE: user
      PASSWORD_DATABASE: pass
    ports:
      - "8080:8080"
    networks:
      - app_multilabs
    depends_on:
      - db

volumes:
  pg_data_app:

networks:
  app_multilabs:
    driver: bridge
