CREATE TABLE tarefa(
  id BIGSERIAL PRIMARY KEY,
  titulo VARCHAR(150) NOT NULL,
  descricao TEXT,
  status VARCHAR(30) NOT NULL,
  prioridade VARCHAR(30) NOT NULL,

  criado_em TIMESTAMP WITHOUT TIME ZONE NOT NULL DEFAULT NOW(),
  atualizado_em TIMESTAMP WITHOUT TIME ZONE
);